### ISSUE TITLE
Sugestão!

### ISSUE THREAD

**Issue by dfrodrig-git** [sergiorebelo/aoc2024#1]
https://github.com/sergiorebelo/aoc2024/blob/bf3e2dd92efcf178dc8302fb39f13cee461089ab/src/main/java/aoc2024/puzzles/Day03.java#L15

Regex usa "\d {1,3}".  O que fazer se houver mais digitos?

Alternativa: "\d+"  (match 1 ou mais digitos)

**Comment by sergiorebelo** [comment]
sim, faz sentido, mas aqui, o enunciado era restritivo em relação ao formato do mul(xxx,yyy). Assumo que se tiver um numero com mais de 3 dífitos está fora do formato.
